# -*- coding: utf-8 -*-

__author__ = 'Guilherme Castelao'
__email__ = 'guilherme@castelao.net'

from importlib import metadata, resources

try:
    from importlib.metadata import version, PackageNotFoundError
except ImportError:  # Python < 3.8
    from importlib_metadata import version, PackageNotFoundError  # type: ignore

try:
    __version__ = version(__name__)
except PackageNotFoundError:
    try:
        from .version import version as __version__
    except ImportError as exc:
        raise ImportError(
            "Failed to find (autogenerated) version.py. "
            "This might be because you are installing from GitHub's tarballs; "
            "use the PyPI distributions instead."
        ) from exc


from oceansdb.woa import WOA
from oceansdb.etopo import ETOPO
from oceansdb.cars import CARS
#from WOA.woa import woa_profile
#from WOA.woa import woa_profile_from_dap
#from WOA.woa import woa_track_from_file
